-- SCRIPT
create database microservice_client;
\c microservice_client;
create schema dbo;
create database microservice_account;
\c microservice_account;
create schema dbo;


-- DB_MICROSERVICE_CLIENT


alter table if exists dbo.clients
    drop constraint if exists FKo28cbg7ns1r1m76bn3sd36eps;

drop table if exists dbo.clients cascade;

drop table if exists dbo.persons cascade;


create table dbo.clients
(
    status    boolean,
    client_id bigint not null unique,
    id        bigint not null,
    password  varchar(255),
    primary key (id)
);


create table dbo.persons
(
    age            integer,
    id             bigint generated by default as identity,
    address        varchar(255),
    gender         varchar(255),
    identification varchar(255),
    name           varchar(255),
    phone          varchar(255),
    primary key (id)
);

alter table if exists dbo.clients
    add constraint FKo28cbg7ns1r1m76bn3sd36eps
        foreign key (id)
            references dbo.persons;


-- DB_MICROSERVICE_ACCOUNT

alter table if exists dbo.movements
    drop constraint if exists FK1a6nru7corjv5b2vidld4ef5r;

drop table if exists dbo.accounts cascade;

drop table if exists dbo.movements cascade;
create table dbo.accounts
(
    amount         numeric(38, 2) not null,
    status         boolean,
    client_id      bigint         not null,
    id             bigint generated by default as identity,
    account_number varchar(255)   not null unique,
    account_type   varchar(255)   not null,
    client_name    varchar(255),
    primary key (id)
);

create table dbo.movements
(
    amount      numeric(38, 2),
    balance     numeric(38, 2),
    account_id  bigint,
    created_at  timestamp(6),
    id          bigint generated by default as identity,
    description varchar(255),
    primary key (id)
);

alter table if exists dbo.movements
    add constraint FK1a6nru7corjv5b2vidld4ef5r
        foreign key (account_id)
            references dbo.accounts;